### ISSUE TITLE
Include IPV in all reports

### ISSUE THREAD

**Issue by AnnieMungai** [OpenSRP/opensrp-client-path-zeir#17]
Update coverage reports to include IPV. The data dictionaries can be found [here](https://docs.google.com/spreadsheets/d/1_2xuIFr71IgqhWqI8Dwmu2BCR2gfD6LtgC2pJ030nTk/edit#gid=705615058). 
- [x] Cohort coverage report (related to [this issue](https://github.com/OpenSRP/opensrp-client-path/issues/171))
- [x] Annual coverage report - CSO (related to [this issue)](https://github.com/OpenSRP/opensrp-client-path/issues/173).
- [x] Annual coverage  report - ZEIR (related to [this issue](https://github.com/OpenSRP/opensrp-client/issues/448)).

**Comment by AnnieMungai** [comment]
v.0.0.4
IPV not computing the right figures: It is showing zero in all reports. 

- [ ] Cohort coverage report (related to this issue)
- [ ] Annual coverage report - CSO (related to this issue).
- [ ] Annual coverage report - ZEIR (related to this issue).

**Comment by AnnieMungai** [comment]
v.0.0.6debug
Looks good!
