### ISSUE TITLE
[DHIS2 Intergration] Checklist for DHIS2 intergration

### ISSUE THREAD

**Issue by dubdabasoduba** [opensrp/opensrp-client-path-zeir#241]
**Mobile**
- [ ] Confirm that the in-app reporting module is added to the ZEIR app correctly 
- [ ] Confirm that the data mapping CSV is correctly updated with the items mentioned [here](https://smartregister.atlassian.net/wiki/spaces/Documentation/pages/1895890945/Technical+Introduction+to+In-App+Reports+DHIS+2+Integration)

**Server**
- [ ] Confirm the current opensrp stage server points to the correct DHIS2 instance
- [ ] Merge the following PRs and redeploy the stage & prod instances
    -  https://github.com/opensrp/opensrp-server-configs/pull/142
    - https://github.com/opensrp/opensrp-server-connector/pull/68
    - https://github.com/opensrp/opensrp-server-web/pull/1035
    - https://github.com/opensrp/opensrp-server-web/pull/1036
 
**OpenSRP web side.**
- [ ] Please go to the locations to be used for the testing and add the DHIS2 organization uuid/id as the `external id` on the location editing form. 
- [ ] For production all the locations would need to have the correct location `external id` added.

**Comment by dubdabasoduba** [comment]
https://github.com/opensrp/opensrp-server-web/issues/1026

**Comment by bennsimon** [comment]
[Changes](https://github.com/opensrp/opensrp-client-path-zeir/pull/244) done on the app.
